services:
  backend1:
    image: python-app
    ports:
      - 9091:9090
    environment:
      - CONTAINER_NAME=python-server-1
    volumes:
      - ./server1.log:/app/users.log

  backend2:
    image: python-app
    ports:
      - 9092:9090
    environment:
      - CONTAINER_NAME=python-server-2
    volumes:
      - ./server2.log:/app/users.log

  backend3:
    image: python-app
    ports:
      - 9093:9090
    environment:
      - CONTAINER_NAME=python-server-3
    volumes:
      - ./server3.log:/app/users.log

  proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
